

name: Make Organization Repositories Public

on:
  workflow_dispatch:

jobs:
  make_public:
    runs-on: ubuntu-latest
    permissions:
        actions: write
        attestations: write
        checks: write
        contents: write
        deployments: write
        id-token: write
        issues: write
        discussions: write
        packages: write
        pages: write
        pull-requests: write
        repository-projects: write
        security-events: write
        statuses: write

    steps:
      - name: Process Repositories and Make Public
        id: process_repos
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const org = context.repo.owner;
            const repoType = 'private';
            let page = 1;
            let processedCount = 0;
            let moreToProcess = false;
            console.log(`${org}`);

            try {
              while (processedCount < 100) {
                const response = await github.rest.repos.listForOrg({
                  org,
                  type: repoType,
                  page,
                  per_page: 100,
                  sort: "updated"
                });

                if (response.data.length === 0) break;

                for (const repo of response.data) {
                  if (processedCount < 100) {
                    if (repo.private) {
                      console.log(`Making ${org}/${repo.name} public...`);
                      await github.rest.repos.update({
                        owner: org,
                        repo: repo.name,
                        private: false,
                      });
                      console.log(`${org}/${repo.name} is now public.`);
                    } else {
                      console.log(`${org}/${repo.name} is already public. Skipping...`);
                    }
                    processedCount++;
                  } else {
                    moreToProcess = true; // Set the flag
                    break;
                  }
                }
                if (response.data.length < 100) break;
                page++;
              }
                core.setOutput('more_to_process', moreToProcess);
                console.log(`Processed ${processedCount} repositories.`);

            } catch (error) {
              console.error("Error processing repositories:", error);
              core.setOutput('more_to_process', false); // Set to false on error
            }

      - name: Dispatch Next Workflow (if needed)
        if: steps.process_repos.outputs.more_to_process == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("Dispatching next workflow run...");
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
            });
